### ISSUE TITLE
BUG: generation fails

### ISSUE THREAD

**Issue by nazimjamil** [lm-a/gen-flow-files#3]
Issue: When running `yarn run gen-flow-files src --out-dir lib` an error is thrown
Steps to reproduce:

1. Install `gen-flow-files` via yarn
2.Run `yarn run gen-flow-files src --out-dir lib`

Expected behaviour:
* `lib` folder to contain types extracted from `src` folder
Actual behaviour:
* Error in code block below is thrown

Environment:
* macOS 10.14.2
* node v8.11.3
* yarn v1.5.1
* flow-bin v^0.93.0
* gen-flow-files v^0.4.1

Additional:
* I have attempted the build version with node v10, latest version of flow-bin and gen-flow-files
* This was working at last run on a different machine 1 month ago

```
njm-scripts [master●●] % yarn run gen-flow-files src --out-dir lib
yarn run v1.5.1
$ /Users/nazimjamil/Sites/njm-test/njm-scripts/node_modules/.bin/gen-flow-files src --out-dir lib
/Users/nazimjamil/Sites/njm-test/njm-scripts/node_modules/@babel/generator/lib/printer.js:277
      throw new ReferenceError(`unknown node of type ${JSON.stringify(node.type)} with constructor ${JSON.stringify(node && node.constructor.name)}`);
      ^

ReferenceError: unknown node of type "Property" with constructor "Node"
    at Generator.print (/Users/nazimjamil/Sites/njm-test/njm-scripts/node_modules/@babel/generator/lib/printer.js:277:13)
    at Generator.printJoin (/Users/nazimjamil/Sites/njm-test/njm-scripts/node_modules/@babel/generator/lib/printer.js:362:12)
    at Generator.printList (/Users/nazimjamil/Sites/njm-test/njm-scripts/node_modules/@babel/generator/lib/printer.js:422:17)
    at Generator.ObjectExpression (/Users/nazimjamil/Sites/njm-test/njm-scripts/node_modules/@babel/generator/lib/generators/types.js:69:10)
    at withSource (/Users/nazimjamil/Sites/njm-test/njm-scripts/node_modules/@babel/generator/lib/printer.js:299:19)
    at Buffer.withSource (/Users/nazimjamil/Sites/njm-test/njm-scripts/node_modules/@babel/generator/lib/buffer.js:185:28)
    at Generator.withSource (/Users/nazimjamil/Sites/njm-test/njm-scripts/node_modules/@babel/generator/lib/printer.js:178:15)
    at Generator.print (/Users/nazimjamil/Sites/njm-test/njm-scripts/node_modules/@babel/generator/lib/printer.js:298:10)
    at Generator.ExportDeclaration (/Users/nazimjamil/Sites/njm-test/njm-scripts/node_modules/@babel/generator/lib/generators/modules.js:114:10)
    at Generator.ExportDefaultDeclaration (/Users/nazimjamil/Sites/njm-test/njm-scripts/node_modules/@babel/generator/lib/generators/modules.js:108:21)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c /Users/nazimjamil/Sites/njm-test/njm-scripts/node_modules/.bin/gen-flow-files src --out-dir lib
Directory: /Users/nazimjamil/Sites/njm-test/njm-scripts
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/nazimjamil/Sites/eps/eps-guild/eps-scripts/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ilyalesik** [comment]
Can you send me the code which you try to convert, please? If code is private, you can send it to ilialesik@gmail.com.

**Comment by nazimjamil** [comment]
I've sent you the contents of a file @ilyalesik

**Comment by ilyalesik** [comment]
@nazimjamil please check new version (`yarn add gen-flow-files@0.4.3`).

**Comment by nazimjamil** [comment]
Hi @ilyalesik I managed to get it to work, my `package.json` only listed `devDependencies`, once I moved one to `dependencies`, it kicked in.

Not sure if this is desired?

**Comment by ilyalesik** [comment]
`devDependencies` / `dependencies` - should not matter.

**Comment by ilyalesik** [comment]
At my own packages I install gen-flow-files as dev dependency. https://github.com/ilyalesik/react-overrides/blob/master/package.json

**Comment by nazimjamil** [comment]
I'm not sure what fixed it then... I'll upgrade just to have the latest version and report back..

**Comment by nazimjamil** [comment]
Can't reproduce this original issue now, so will close the issue for now.

**Comment by ilyalesik** [comment]
Ok. If the problem will reproduce, you can just reopen the issue.
